version: '3'

services:
  jira:
    image: git.hisoft.com.vn:5050/core/jira:latest
    volumes:
      - "jira-data:/var/atlassian/application-data/jira"
      - "jira-config:/opt/atlassian/etc/"
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: mysql:8
    volumes:
      - "db:/var/lib/mysql"
    env_file:
      - ./.env

volumes:
  jira-data:
  jira-config:
  db:
